ALTER TABLE User
  DROP COLUMN username,
  DROP COLUMN first_name,
  DROP COLUMN last_name,
  DROP COLUMN date_of_birth,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN name VARCHAR(255) NOT NULL,
  ADD COLUMN google_id VARCHAR(255);